### ISSUE TITLE
Firefox extension?

### ISSUE THREAD

**Issue by iam-cult** [mastermajorman/youtube_dislike#1]
Just wondering if you could create a Firefox extension, awesome work btw.

**Comment by mastermajorman** [comment]
Sure thing. I should have time within the next 24hr. When it's done, I'll put a link here and update the README.

**Comment by notboeing747** [comment]
What you're doing is amazing. Thank you.

**Comment by mastermajorman** [comment]
I submitted the extension to the Firefox Add-on store. If you don't want to wait, clone the repo, go to "about:debugging#/runtime/this-firefox" page in Firefox, click on "Load Temporary Add-on", and then submit the Firefox folder by selecting one of the files in it.

I'll update the README when it's approved, but for now I'll mark this as resolved.
