### ISSUE TITLE
data source

### ISSUE THREAD

**Issue by korczas** [mastermajorman/youtube_dislike#2]
I see that you are fetching data from aws, but I am curious how aws get that data?

**Comment by mastermajorman** [comment]
It's a pretty straightforward setup. Amazon API Gateway with a Lamba function behind it for the YouTube Data API call. I used it to hide my key. If it was just an extension for myself, I wouldn't have gone through the lengths to set it up.

If this is in reference to the application not working, it's not my fault. I requested an increase to the YouTube Data API, but they haven't gotten back to me in a more than a week. I get over 20k requests a day at this point, while my client only allows 10k request points per day.

**Comment by korczas** [comment]
Good job man. Fingers crossed they will raise the limit, as the number of users will grow overtime :)
